---
- name: Upgrade Ubersmith
  hosts: local
  any_errors_fatal: true

  pre_tasks:

    - name: Check for .ubersmith_installer.ini
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.ubersmith_installer.ini"
      register: installer_config
      tags:
        - upgrade

    - name: Fail if installer configuration is not present
      ansible.builtin.fail:
        msg: "Ubersmith installer configuration file is not present, please run configure.sh"
      when: not installer_config.stat.exists
      tags:
        - upgrade

  vars:
    ubersmith_home: >-
      {{ lookup('ini', 'ubersmith_home section=ubersmith_installer
      file={{ ansible_user_dir }}/.ubersmith_installer.ini') }}
    virtual_host: >-
      {{ lookup('ini', 'virtual_host section=ubersmith_installer
      file={{ ansible_user_dir }}/.ubersmith_installer.ini') }}
    admin_email: >-
      {{ lookup('ini', 'admin_email section=ubersmith_installer
      file={{ ansible_user_dir }}/.ubersmith_installer.ini') }}
    notify_email: >-
      {{ lookup('ini', 'admin_email section=ubersmith_installer
      file={{ ansible_user_dir }}/.ubersmith_installer.ini') }}
    ubersmith_installed_version: >-
      {{ lookup('ini', 'ubersmith_installed_version section=ubersmith_installer
      file={{ ansible_user_dir }}/.ubersmith_installer.ini') }}
    ubersmith_major_version: "5"
    lets_encrypt_certificate: >-
      {{ lookup('ini', 'lets_encrypt_certificate section=ubersmith_installer
      file={{ ansible_user_dir }}/.ubersmith_installer.ini default=yes') }}
    interactive: true

  roles:
    - common
    - ubersmith
