---

  - name: install snapd
    apt:
      name: snapd
      state: present 
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install snapd
    yum:
      name: snapd
      state: present 
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: start and enable snapd service
    ansible.builtin.service:
      name: snapd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: enable snap classic support
    ansible.builtin.file:
      src: /var/lib/snapd/snap
      dest: /snap
      owner: root
      group: root
      state: link
    when: ansible_os_family == "RedHat"
