"""Tests for ubersmith_installer.secrets."""

from __future__ import annotations

import string

from ubersmith_installer.secrets import (
    DEFAULT_PASSWORD_LENGTH,
    appliance_password_paths,
    get_or_create_password,
    ubersmith_password_paths,
)


def test_generates_new_password_and_creates_file(tmp_path):
    path = tmp_path / "sub" / ".ubersmith_example.com_root_db_pass"

    password = get_or_create_password(path)

    assert path.exists()
    assert len(password) == DEFAULT_PASSWORD_LENGTH
    assert all(c in string.ascii_letters + string.digits for c in password)
    assert path.read_text().strip() == password


def test_calling_again_returns_same_password(tmp_path):
    path = tmp_path / ".ubersmith_example.com_ubersmith_db_pass"

    first = get_or_create_password(path)
    second = get_or_create_password(path)

    assert first == second


def test_file_mode_is_restrictive(tmp_path):
    path = tmp_path / ".ubersmith_example.com_root_db_pass"

    get_or_create_password(path)

    mode = path.stat().st_mode & 0o777
    assert mode == 0o600


def test_existing_arbitrary_content_returned_unchanged(tmp_path):
    # Simulates a password file generated by the old Ansible `password`
    # lookup, which may include punctuation outside our own charset.
    path = tmp_path / ".ubersmith_example.com_root_db_pass"
    existing = "abc!@#$%^&*()_+-=[]{}xyz123"
    path.write_text(existing + "\n")

    result = get_or_create_password(path)

    assert result == existing


def test_existing_content_is_stripped(tmp_path):
    path = tmp_path / ".ubersmith_example.com_root_db_pass"
    path.write_text("  spacedpass  \n")

    result = get_or_create_password(path)

    assert result == "spacedpass"


def test_ubersmith_password_paths(tmp_path):
    paths = ubersmith_password_paths(tmp_path, "example.com")

    assert paths["root_db_pass"] == tmp_path / ".ubersmith_example.com_root_db_pass"
    assert paths["ubersmith_db_pass"] == tmp_path / ".ubersmith_example.com_ubersmith_db_pass"


def test_appliance_password_paths(tmp_path):
    paths = appliance_password_paths(tmp_path, "app.example.com")

    assert paths["root_db_pass"] == tmp_path / ".appliance_app.example.com_root_db_pass"
    assert paths["appliance_db_pass"] == tmp_path / ".appliance_app.example.com_appliance_db_pass"
    assert paths["appliance_user_pass"] == tmp_path / ".appliance_app.example.com_appliance_user_pass"
    assert paths["appliance_xmlrpc_pass"] == tmp_path / ".appliance_app.example.com_appliance_xmlrpc_pass"
