"""Password file generation/lookup for the Ubersmith installer.

This module replaces Ansible's ``lookup('password', path)`` and
``lookup('password', path + ' chars=ascii_letters,digits')`` calls used in
``roles/ubersmith/vars/main.yml`` (lines 24-25) and
``roles/appliance/vars/main.yml`` (lines 4-7):

    mysql_root_password: "{{ lookup('password', ansible_user_dir + '/.ubersmith_' + main_virtual_host + '_root_db_pass chars=ascii_letters,digits') }}"
    mysql_ubersmith_password: "{{ lookup('password', ansible_user_dir + '/.ubersmith_' + main_virtual_host + '_ubersmith_db_pass') }}"

    mysql_root_password: "{{ lookup('password', ansible_user_dir + '/.appliance_' + app_virtual_host + '_root_db_pass chars=ascii_letters,digits') }}"
    mysql_appliance_password: "{{ lookup('password', ansible_user_dir + '/.appliance_' + app_virtual_host + '_appliance_db_pass') }}"
    mysql_appliance_user_password: "{{ lookup('password', ansible_user_dir + '/.appliance_' + app_virtual_host + '_appliance_user_pass') }}"
    uberapp_user_password: "{{ lookup('password', ansible_user_dir + '/.appliance_' + app_virtual_host + '_appliance_xmlrpc_pass') }}"

Ansible's ``password`` lookup semantics: given a file path, if the file
already exists, its (stripped) contents are read and returned unchanged --
this is what lets an existing customer's password files keep working when
read by this new CLI, no matter what character set Ansible originally used
to generate them (Ansible's own default is a large keyboard-ish charset
including punctuation). If the file does *not* exist, a new random password
is generated, written to the file (parent directories created as needed),
and returned.

Deliberate simplification vs. Ansible's default charset: when *generating* a
brand new password, this module always uses letters+digits only (via
``secrets.choice``), regardless of what Ansible's charset would have been.
This is safe for compatibility -- existing files are always read back
verbatim, regardless of how they were originally generated -- and it avoids
punctuation characters that would otherwise need careful escaping when these
passwords are later interpolated into shell commands (e.g. ``mysql -p...``)
and docker-compose environment variables/.env files.
"""

from __future__ import annotations

import secrets
import string
from pathlib import Path

#: Default length of newly generated passwords, matching Ansible's
#: ``lookup('password', ...)`` default.
DEFAULT_PASSWORD_LENGTH = 20

#: Safe alphanumeric charset used for newly generated passwords. See module
#: docstring for why this differs from Ansible's own default charset.
LETTERS_DIGITS = string.ascii_letters + string.digits

_CHARSETS = {
    "letters_digits": LETTERS_DIGITS,
}


def _generate_password(chars: str, length: int) -> str:
    alphabet = _CHARSETS.get(chars, chars)
    return "".join(secrets.choice(alphabet) for _ in range(length))


def get_or_create_password(
    path: Path,
    chars: str = "letters_digits",
    length: int = DEFAULT_PASSWORD_LENGTH,
) -> str:
    """Read an existing password file, or generate and persist a new one.

    Mirrors Ansible's ``lookup('password', path)`` behavior:

    * If ``path`` exists, its content is read and returned stripped, exactly
      as-is -- no validation of its character set is performed, since files
      generated by the previous Ansible-based installer may use a different
      (wider) charset than this module generates.
    * If ``path`` does not exist, a new password is generated using
      Python's ``secrets`` module (cryptographically secure, unlike
      ``random``), written to ``path`` (creating parent directories if
      needed, and setting a restrictive file mode of ``0600``), and
      returned.

    :param path: Location of the password file.
    :param chars: Charset key to use when generating a *new* password.
        Currently only ``"letters_digits"`` (the default) is supported;
        this parameter exists to mirror Ansible's ``chars=`` lookup option
        and to allow future charsets without changing the call signature.
    :param length: Length of a newly generated password.
    """
    path = Path(path)
    if path.exists():
        return path.read_text().strip()

    password = _generate_password(chars, length)
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    path.write_text(password)
    path.chmod(0o600)
    return password


def ubersmith_password_paths(home_dir: Path, main_virtual_host: str) -> dict:
    """Return the two password file paths used by ``roles/ubersmith``.

    Mirrors ``roles/ubersmith/vars/main.yml`` lines 24-25, where
    ``ansible_user_dir`` is the user's home directory and
    ``main_virtual_host`` is the first entry of the comma-split
    ``virtual_host`` variable.
    """
    home_dir = Path(home_dir)
    return {
        "root_db_pass": home_dir / f".ubersmith_{main_virtual_host}_root_db_pass",
        "ubersmith_db_pass": home_dir / f".ubersmith_{main_virtual_host}_ubersmith_db_pass",
    }


def appliance_password_paths(home_dir: Path, app_virtual_host: str) -> dict:
    """Return the four password file paths used by ``roles/appliance``.

    Mirrors ``roles/appliance/vars/main.yml`` lines 4-7.
    """
    home_dir = Path(home_dir)
    return {
        "root_db_pass": home_dir / f".appliance_{app_virtual_host}_root_db_pass",
        "appliance_db_pass": home_dir / f".appliance_{app_virtual_host}_appliance_db_pass",
        "appliance_user_pass": home_dir / f".appliance_{app_virtual_host}_appliance_user_pass",
        "appliance_xmlrpc_pass": home_dir / f".appliance_{app_virtual_host}_appliance_xmlrpc_pass",
    }
