---

  - name: verify docker is installed
    command: command -v docker
    register: docker_result
    failed_when: docker_result.rc != 0

  - name: install docker-compose
    pip:
      name: docker-compose
      state: latest
      extra_args: "--user"

  # - name: create local ubersmith unix user account
  #   user:
  #     name: ubersmith
  #     comment: "Ubersmith Application User"
  #   tags:
  #     - uber_user