---

  - name: Output OS and Version
    debug:
      msg: "This host is running {{ ansible_distribution }} {{ ansible_distribution_version }}."
    tags:
      - os

  - name: Output Running Kernel
    debug:
      msg: "This host is running Linux kernel version {{ ansible_kernel }}."
    tags:
      - os 

  - name: Verify OS Distribution is Debian, CentOS, or Ubuntu
    assert:  
      that:
        - "ansible_distribution in supported_os"
      msg: "Ensure Host is running Debian, CentOS, or Ubuntu."
    tags:
      - os

  - name: Verify Ubuntu OS Distribution Version and Kernel
    assert:  
      that:
        - "{{ ansible_distribution_version is version_compare(supported_ubuntu_ver, '>=') }}"
        - "{{ ansible_kernel is version_compare('4.4.0', '>=' ) }}"
      msg: "Ensure Host is running supported Ubuntu LTS with 4.4.0+ kernel"
    when: ansible_distribution == 'Ubuntu'
    tags:
      - os

  - name: Verify CentOS OS Distribution Version and Kernel
    assert:  
      that:
        - "ansible_distribution_version|int >= supported_centos_ver"
        - "{{ ansible_kernel is version_compare('3.10.0-693', '>=' ) }}"
      msg: "Ensure Host is running supported CentOS and kernel newer than 3.10.0-693"
    when: ansible_distribution == 'CentOS'
    tags:
      - os

  - name: Verify Debian OS Distribution Version and Kernel
    assert:  
      that:
        - "ansible_distribution_version|int >= supported_debian_ver"
        - "{{ ansible_kernel is version_compare('4.0', '>=' ) }}"
      msg: "Ensure Host is running supported Debian"
    when: ansible_distribution == 'Debian'
    tags:
      - os

  # The installation instructions require Docker is installed before the installer is run.
  # Since there are many platforms users could be trying to install on, it's easier to
  # let the sysadmin handle the installation of Docker.
  - name: verify docker is installed
    shell: command -v docker
    register: docker_result
    ignore_errors: true
    tags:
      - upgrade
  
  # If we can't find Docker, we can't proceed.
  - name: output error when docker is not installed
    fail:
      msg: "Docker does not appear to be installed. Please install Docker (https://docs.docker.com/engine/installation/)."
    when: docker_result.rc != 0
    tags:
      - upgrade

  # Check the version reported by the running version of Docker.
  - name: verify docker version
    shell: docker version --format '{{ '{{' }} .Server.Version {{ '}}' }}'
    register: docker_version
    tags:
      - upgrade
  
  # Give the administrator an opportunity to do the right thing or shoot themselves in the foot.
  - name: output error when docker is too old
    pause:
      prompt: "The Docker version installed is not supported. Please upgrade Docker (https://docs.docker.com/engine/installation/). If you're sure this is OK, press CTRL+C and then c. To abort the installation, press CTRL+c and then a."
    when: docker_version.stdout[:5] is version_compare(docker_ok_version, '<=' )
    tags:
      - upgrade

  # Enable the Docker service in the event the installer / sysadmin did not.
  - name: ensure the docker service is enabled
    service:
      name: docker
      enabled: yes
    when: 
      - ansible_os_family != "Darwin"
      - ansible_os_family != "Windows"

  # Install the docker-compose application using pip.
  - name: install docker-compose
    pip:
      name: docker-compose
      state: present
      version: "{{ docker_compose_version }}"
      extra_args: "--user"
    when:
      - interactive
    tags:
      - upgrade
