---
  # The installation instructions require Docker is installed before the installer is run.
  # Since there are many platforms users could be trying to install on, it's easier to
  # let the sysadmin handle the installation of Docker.
  - name: verify docker is installed
    shell: command -v docker
    register: docker_result
    ignore_errors: true
    tags:
      - upgrade
  
  # If we can't find Docker, we can't proceed.
  - name: output error when docker is not installed
    fail:
      msg: "Docker does not appear to be installed. Please install Docker (https://docs.docker.com/engine/installation/)."
    when: docker_result.rc != 0
    tags:
      - upgrade

  # Check the version reported by the running version of Docker.
  - name: verify docker version
    shell: docker version --format '{{ '{{' }} .Server.Version {{ '}}' }}'
    register: docker_version
    tags:
      - upgrade
  
  # Give the administrator an opportunity to do the right thing or shoot themselves in the foot.
  - name: output error when docker is too old
    pause:
      prompt: "The Docker version installed is not supported. Please upgrade Docker (https://docs.docker.com/engine/installation/). If you're sure this is OK, press CTRL+C and then c. To abort the installation, press CTRL+c and then a."
    when: docker_version.stdout[:5] is version_compare(docker_ok_version, '<=' )
    tags:
      - upgrade

  # Enable the Docker service in the event the installer / sysadmin did not.
  - name: ensure the docker service is enabled
    service:
      name: docker
      enabled: yes
    when: 
      - ansible_os_family != "Darwin"
      - ansible_os_family != "Windows"

  # Install the docker-compose application using pip.
  - name: install docker-compose
    pip:
      name: docker-compose
      state: latest
      extra_args: "--user"
    tags:
      - upgrade