---

  appliance_root: /var/www/appliance_root
  mysql_root_password: "{{ lookup('password', '/tmp/' + inventory_hostname + '_root_db_pass') }}"
  mysql_appliance_password: "{{ lookup('password', '/tmp/' + inventory_hostname + '_appliance_db_pass') }}"
  mysql_appliance_user_password: "{{ lookup('password', '/tmp/' + inventory_hostname + '_appliance_user_pass') }}"
