---

  appliance_root: /var/www/appliance_root
  mysql_root_password: "{{ lookup('password', '/tmp/' + inventory_hostname + '_root_db_pass') }}"
  mysql_appliance_password: "{{ lookup('password', '/tmp/' + inventory_hostname + '_appliance_db_pass') }}"
  mysql_appliance_user_password: "{{ lookup('password', '/tmp/' + inventory_hostname + '_appliance_user_pass') }}"

  appliance_version: 4.0.6
  
  containers:
    backup_version: 2.4.4
    appliance_db_version: 5.6
    appliance_web_version: "{{ appliance_version }}.0.0"
    appliance_cron_version: 2.0