name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: tar zcf ../ubersmith-installer-${{ github.ref_name }}.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: ../ubersmith-installer-${{ github.ref_name }}.tar.gz
      - name: Checksums
        uses: wangzuo/action-release-checksums@v1