name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: tar --exclude='./.git' --transform 's,^,ubersmith-installer-${{ github.ref_name }}/,' -zcf ../ubersmith-installer-${{ github.ref_name }}.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            name: Ubersmith Installer ${{ github.ref_name }}
            files: ../ubersmith-installer-${{ github.ref_name }}.tar.gz
      - name: Checksums
        uses: wangzuo/action-release-checksums@v1.0.1